### ISSUE TITLE
Dynamic Segment Offering test vectors return "Failed loading XML file"

### ISSUE THREAD

**Issue by asrashley** [Dash-Industry-Forum/Test-Vectors#41]
Trying test vectors 1 .. 3 from:
http://dashif.org/test-vectors/#DSO

All produce an error of "Failed loading XML file"

**Comment by AdithyanIlangovan** [comment]
The problem is currently fixed.

Earlier, each of the above mentioned links were passing query parameters that were pointing to a dead link.
- For some reason, the main file had been renamed from "manifest.mpd" to "manifest_bug.mpd".
- Maybe,  the manifest file had a bug (This will be further looked into later)
- The old links were still pointing to "manifest.mpd"

Currently, this issue is fixed.
We point to alternate working streams (for later reference : 1b/qualcomm) and all the three vectors can now be used.
If issues exist, please report.
