### ISSUE TITLE
Missing period ID in live test vector with remote element?

### ISSUE THREAD

**Issue by ghost** [Dash-Industry-Forum/Test-Vectors#55]
Hi
I  was  referring to the test vector http://vm2.dashif.org/livesim/periods_60/xlink_30/insertad_1/testpic_2s/Manifest.mpd

The period which refers to xlink, doesn't have an ID associated. As  I understand a period ID is mandatory for dynamic stream? The resolved remote period does have an ID, but that ID shouldn't be used as using that will not guarantee uniqueness of period IDs in the main content mpd?

**Comment by waqarz** [comment]
@AdithyanIlangovan please check

**Comment by AdithyanIlangovan** [comment]
@KarishmaBagga 
Thanks for raising the issue.Yes, there seems to be some confusion you mentioned.
I looked into the DASH standard and found two points relevant to this.

The first was related to period ID,
- If the MPD@type is "dynamic", then this attribute (**ID**) shall be present and shall not change in case the MPD is updated.

This is as you say.

But the second was, 
- All XLINK attributes initially present in the MPD shall be removed after dereferencing is completed.

This means that all the attributes, including the period ID will be removed and overwritten with the resolved remote period attributes. So, it cannot be said that :
> The resolved remote period does have an ID, but that ID shouldn't be used as using that will not guarantee uniqueness of period IDs in the main content mpd?

Summary : The dereferenced .mpd will have an ID associated with it that shall be derived from remote .mpd.

**Comment by ghost** [comment]
@AdithyanIlangovan  But then period IDs have to be unique in a dynamic MPD. how do we ensure that if we over-ride the period ID and use the one from remote MPD? I thought it meant the xlink attributes and not the period attributes

**Comment by AdithyanIlangovan** [comment]
@KarishmaBagga This is unclear to me too. 
Even if I set the xlink period to have an ID, as the standard mentions, this shall be overwritten with attribute of remote MPD.

Two possible solutions:

- Do not specify ID in remote MPD and use ID attribute only in xlink period.
- Take care to specify unique ID in remote MPD and do not use ID attribute in xlink period.

**Comment by ghost** [comment]
@AdithyanIlangovan You cannot guarantee correctness in option 2 because these 2 MPDs aren't related and one remote mpd may be used in multiple contents, right?

I''d say option 1 but then to think of it an xlink might resolve to a remote mpd with multiple periods as well, right?

**Comment by AdithyanIlangovan** [comment]
@KarishmaBagga 
Agreed. Option 1 is better.

For the sake of completion, the original test vector : http://vm2.dashif.org/livesim/periods_60/xlink_30/insertad_1/testpic_2s/Manifest.mpd
is a DASH conforming vector. 
Because it guarantees option 2. It takes care to specify unique ID in remote MPD always.
Do you agree?

I would also implement another test vector for option 1.
Can I consider this closed now?

**Comment by ghost** [comment]
@AdithyanIlangovan you mean in the mentioned test vector we ensure that the remote period id is unique for the main content mpd?

**Comment by AdithyanIlangovan** [comment]
@KarishmaBagga Yes that is correct. It is always unique.

**Comment by jyotikadian** [comment]
@AdithyanIlangovan In the mentioned test vector, remote period ID changes on every mpd (main content) refresh for a period refered using xlink onLoad resolution. Is this intended? Because if manifest is refreshed while playing a remote period content, then we will lose the reference as its remote period ID would have changed now.    
Remote period ID always remains same for a xlink period in the following test vector:
http://vm2.dashif.org/livesim/periods_60/xlink_30/testpic_2s/Manifest.mpd

**Comment by waqarz** [comment]
> Two possible solutions:
>
> Do not specify ID in remote MPD and use ID attribute only in xlink period.
> Take care to specify unique ID in remote MPD and do not use ID attribute in xlink period.

I do believe we had related discussion in the IOP group in the context of Ad-insertion. If IOP document does not clarify the issue currently, it should. I open up this issue for IOP discussion in this case.

**Comment by dsilhavy** [comment]
> I do believe we had related discussion in the IOP group in the context of Ad-insertion. If IOP document does not clarify the issue currently, it should. I open up this issue for IOP discussion in this case.

I think the discussion was related to the start attribute of the remote period. For instance, if the first period is resolved via Xlink the remote period needs to have a start attribute, otherwise it is not a regular period and will not be played. As far as I remember, the solution was to include the start time of the period in the XLink request. That way the XLink resolver can add the right timing.

**Comment by ghost** [comment]
Yes I do remember the discussion and presentation around start time but none related to ID.
I feel there's an ambiguity in the sense that iop doesn't mention about how period IDs would be resolved for xlink. If we ignore remote period id and honour only the period id in the mpd then am not sure how will we derive period ids in case of multiple periods in the remote mpd. On the other hand In case we instead honour the remote mpd period id then I don't think so it's practical to expect the remote period id to be unique for the mpd

**Comment by waqarz** [comment]
Please discuss here: https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/121 in IOP

**Comment by waqarz** [comment]
Close here, discuss in https://github.com/Dash-Industry-Forum/DASH-IF-IOP/issues/121
