### ISSUE TITLE
Multiperiod Test Vector 1 has unexpected PTO

### ISSUE THREAD

**Issue by davemevans** [Dash-Industry-Forum/Test-Vectors#88]
http://dash.akamaized.net/dash264/TestCases/5a/nomor/1.mpd, for example, specifies a presentationTimeOffset of 1024 (= 0.083333s), but the baseMediaDecodeTime of the first segment is 0.

When using dash.js in Chrome, the append of the first segment fails and the player stops completely since the decode time of the first sample is negative.

Should there be a presentationTimeOffset when the media starts at zero?

There may be other assets exhibiting the same behaviour.

**Comment by niteeshbhat** [comment]
After checking the mp4 box, it is observed that the base media decode time is indeed zero, but the earliestPresentationTime in sidx is 1024. Hence there is  a composition offset. However there might be an A/V sync issue.

Closing this issue here. 
And opening a separate issue for A/V sync : https://github.com/Dash-Industry-Forum/Test-Vectors/issues/89
